name: CI/CD con SonarQube y Pruebas en EZsGE

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  test-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Sonar necesita el historial completo

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Versión más estable

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verificar errores con Pylint
        run: |
          pylint **/*.py || true

      - name: Ejecutar pruebas unitarias
        run: |
          python -m unittest discover tests

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
